# Generated by Django 6.0.3 on 2026-04-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FishSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nazwa gatunku')),
                ('temp_min', models.FloatField(help_text='Minimalna temperatura [°C]')),
                ('temp_max', models.FloatField(help_text='Maksymalna temperatura [°C]')),
                ('ph_min', models.FloatField(help_text='Minimalne pH')),
                ('ph_max', models.FloatField(help_text='Maksymalne pH')),
                ('min_tank_volume', models.PositiveIntegerField(help_text='Minimalny litraż [L]')),
                ('bioload_index', models.FloatField(help_text='Współczynnik obciążenia biologicznego')),
                ('zone', models.CharField(choices=[('TOP', 'Tafle wody'), ('MID', 'Środkowe partie'), ('BTM', 'Przy dnie')], default='MID', max_length=3)),
                ('aggression_level', models.IntegerField(default=1, help_text='Poziom agresji (1-5)')),
            ],
        ),
    ]
