# Generated by Django 6.0.3 on 2026-04-03 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishspecies',
            name='is_schooling',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fishspecies',
            name='aggression_level',
            field=models.IntegerField(default=1, help_text='Poziom agresji (1-3)'),
        ),
    ]
