# Generated by Django 6.0.3 on 2026-04-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fishspecies_is_schooling_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishspecies',
            name='adult_size',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='fishspecies',
            name='origin_region',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
