# Generated by Django 6.0.3 on 2026-04-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_fishspecies_adult_size_fishspecies_origin_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishspecies',
            name='hardness_max',
            field=models.FloatField(default=15.0, help_text='Maksymalna twardość [dH]'),
        ),
        migrations.AddField(
            model_name='fishspecies',
            name='hardness_min',
            field=models.FloatField(default=5.0, help_text='Minimalna twardość [dH]'),
        ),
    ]
