# Generated by Django 6.0.3 on 2026-04-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_fishspecies_hardness_max_fishspecies_hardness_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishspecies',
            name='latin_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Nazwa łacińska'),
        ),
    ]
