# Generated by Django 6.0.3 on 2026-04-04 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fishspecies_latin_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishspecies',
            name='source_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link do źródła'),
        ),
    ]
