# Generated by Django 6.0.3 on 2026-04-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_fishspecies_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishspecies',
            name='is_solitary',
            field=models.BooleanField(default=False, verbose_name='Ryba samotnicza'),
        ),
    ]
